project:
  type: website

website:
  title: "AI experiments"
  google-analytics:
    tracking-id: "G-B8P88P732Y"
    anonymize-ip: false
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/geirfreysson/ai-experiments
      - icon: twitter
        href: https://twitter.com/geirfreysson
format:
  html:
    fontsize: 1.15em;



