project:
  type: website
  preview:
    port: 3000
  pre-render: 
    - change_future_posts_to_draft.py
website:
  image: blog-logo.svg
  title: "Geir's notes"
  favicon: blog-logo.svg
  search: false
  twitter-card:
    site: "@geirfreysson"
  open-graph: true
  site-url: "https://www.geirfreysson.com"
  navbar:
    logo: blog-logo.svg
    right:
      - text: "about"
        href: about.qmd
      - text: "subscribe"
        href: https://docs.google.com/forms/d/e/1FAIpQLSej7F65xN4OynA7c1AkPpd41fEuyWT3_06Op5IW0mUs3TxoGg/viewform
format:
  html:
    fontsize: 1.15em;
    css: styles.css



