project:
  type: website

website:
  title: "Geir's notes"
  image: blog-logo.svg
  favicon: blog-logo.svg
  search: false
  google-analytics:
    tracking-id: "G-B8P88P732Y"
    anonymize-ip: false
  navbar:
    right:
      - text: "![](/blog-logo.svg)"
        href: content/experience/index.qmd
format:
  html:
    fontsize: 1.15em;
    css: styles.css



