project:
  type: website
  preview:
    port: 3000
  render:
    - "*.qmd"
    - "posts/**"
    - "!Geirfreysson redesign/"
  pre-render:
    - change_future_posts_to_draft.py
  post-render:
    - assign_post_numbers.py
website:
  image: blog-logo.svg
  title: "Geir's notes"
  favicon: blog-logo.svg
  search: false
  twitter-card:
    site: "@geirfreysson"
  open-graph: true
  site-url: "https://www.geirfreysson.com"
format:
  html:
    fontsize: 1.15em;
    css: styles.css



