project:
  type: website

website:
  title: "AI experiments"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/geirfreysson/ai-experiments
      - icon: twitter
        href: https://twitter.com/geirfreysson
format:
  html:
    theme: cosmo
    css: styles.css



