project:
  type: website

website:
  title: "Geir's notes"
  image: blog-logo.svg
  google-analytics:
    tracking-id: "G-B8P88P732Y"
    anonymize-ip: false
  navbar:
    right:
      - icon: images/blog-logo.svg
format:
  html:
    fontsize: 1.15em;



